name: ci

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Maven test
        run: mvn test

      - name: Code Coverage (min -> 75%)
        run: mvn jacoco:prepare-agent test jacoco:report jacoco:check

      - name: Maven build
        run: mvn clean package